linz/geostore

- .github/workflows/ci.yml
- infra/app.py
- infra/tests/test_stack.py
- infra/tests/test_storage_bucket.py
`DEPLOY_ENV` variable is more meaningful to me.
> chore: rename deploy target var ENVIRONMENT_TYPE to DEPLOY_ENV

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .gitignore
- .pre-commit-config.yaml
- .pylintrc
- .yamllint.yml
- README.md
- requirements-dev.txt
- tests/test_sample.py
Would this be a useful addition to the pre-commit linting we already have in place?
Also wondering if we could merge the dev env linting and CI linting by running `pre-commit run --all-files` in CI.
> Pre commit linting

- .github/dependabot.yml
Based on https://github.com/linz/template-python-hello-world
> test(lint): Add Dependabot support for GitHub Actions

- README.md
This format keeps the bullet points together as a single list rather
than one list per point, marks the code as belonging underneath the
parent bullet point, and fixes the heading levels.
> feat: Tweak documentation formatting

- .github/workflows/ci.yml
Reverts linz/geospatial-data-lake#61
> revert: "ci: wait if another CI AWS stack already exists"

- backend/endpoints/datasets/create.py
- backend/endpoints/datasets/get.py
- backend/endpoints/datasets/update.py
The variable is overridden on the next line.
> refactor: Remove redundant code

- .github/workflows/ci.yml
> ci: Cache NPM downloads

- .github/workflows/ci.yml
> ci: Cache pip downloads

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- README.md
> ci: Use specific Ubuntu version for pipelines

- backend/tests/test_datasets_endpoint.py
Should be ready once https://github.com/linz/geospatial-data-lake/pull/99 is merged.
> test: Randomise test data

- .github/workflows/ci.yml
- infra/datalake/api_stack.py
- infra/datalake/processing_stack.py
- poetry.lock
- pyproject.toml
> feat: Use Python 3.8

- .github/workflows/ci.yml
Use CI AWS account for our CI jobs
> ci: use CI AWS account for CI

- README.md
- package-lock.json
- reset-dev-env.bash
> feat: Create dev env setup script & instructions

- .github/workflows/ci.yml
- .gitmodules
- datalake/backend/processing/check_stac_metadata/Dockerfile
- datalake/backend/processing/check_stac_metadata/task.py
- datalake/backend/tests/test_check_stac_metadata.py
- datalake/backend/tests/utils.py
- datalake/processing_stack.py
- poetry.lock
- pyproject.toml
- reset-dev-env.bash
- tests/conftest.py
Based on https://github.com/linz/geospatial-data-lake/pull/132
> feat: Validate metadata

- .github/workflows/deploy.yml
- .github/workflows/test.yml
Closes issue #148, as seen in https://github.com/linz/geospatial-data-lake/runs/1586803853?check_suite_focus=true#step:6:1
> feat: Split up deploy and test pipelines

- .github/workflows/test.yml
> ci: Run tests in parallel with linter

- datalake/backend/processing/check_stac_metadata/Dockerfile
- poetry.lock
- pyproject.toml
> fix: Include boto3 dependency for metadata validation

- .github/workflows/test.yml
- datalake/backend/processing/check_stac_metadata/Dockerfile
- poetry.lock
- pyproject.toml
- reset-dev-env.bash
Follow-up to https://github.com/linz/geospatial-data-lake/pull/154, since the original code was installing the development packages.
> feat: Install only production dependencies in Docker container

- datalake/backend/processing/check_stac_metadata/task.py
- datalake/backend/tests/test_check_stac_metadata.py
Blocked by https://github.com/linz/geospatial-data-lake/pull/158
> feat: Validate stac files recursively

- datalake/backend/processing/check_flat_directory_structure/Dockerfile
- datalake/backend/processing/check_flat_directory_structure/task.py
- datalake/backend/processing/check_stac_metadata/task.py
- datalake/backend/tests/test_check_stac_metadata.py
- datalake/backend/tests/utils.py
- datalake/processing_stack.py
> feat: Validate flat directory structure

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- package-lock.json
- package.json
This PR also upgrades CDK version to latest (which was until now used by CI but not for local dev)
> ci: use same Node and CDK versions for local development and CI

- app.py
- cdk.json
- datalake/backend/processing/check_stac_metadata/Dockerfile
- datalake/backend/processing/content_iterator/task.py
- datalake/backend/tests/conftest.py
- datalake/backend/tests/test_processing_stack.py
- datalake/backend/tests/utils.py
- datalake/dataset_source_stack.py
- datalake/processing_stack.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
> test(infra): add processing stack tests

- .github/workflows/test.yml
- .gitignore
- README.md
- poetry.lock
- pyproject.toml
Closes https://github.com/linz/geospatial-data-lake/issues/119.
> test: Verify test coverage

- app.py
- cdk.json
- datalake/backend/tests/test_processing_stack.py
- datalake/staging_stack.py
Change to align with our naming convention and HLD . In this change I introduced bucket name constant instead of storing bucket name in `cdk.json` file.
> refactor(infra): rename 'source_stack' to 'staging_stack' (closes #74)

- .github/workflows/test.yml
It's already run by `pre-commit`.
> fix: Remove duplicate shellcheck run

- README.md
- poetry.lock
- pyproject.toml
The IPython debugger is much more user friendly than the standard
library Python debugger (pdb).
> feat: Install ipdb for development

- app.py
- datalake/backend/tests/test_processing_stack.py
Pull CDK into a `main` method to allow side-effect-free import of the
constants.
> refactor: Reference app.py constants

- README.md
- app.py
- datalake/api_stack.py
- datalake/users_stack.py
closes #206
Roles assuming tested manually and works
```
$aws sts assume-role
--role-arn arn:aws:iam::<AWS_ACCOUNT_ID>:role/geospatial-data-lake-user-accountreadwriterole9368-14HH9GDL5A9FL
--role-session-name linz-datalake-assumed-role
$ aws lambda invoke --function-name datasets-endpoint --invocation-type RequestResponse --payload '{"httpMethod": "GET", "body": {}}' response.json && cat response.json
```
> feat(infra): user roles stack implementation

- USAGE.md
> docs: add lambda endpoints usage documentation

- reset-dev-env.bash
Otherwise the command will fail when a directory does not exist.
> fix: Force remove package directories

- datalake/backend/tests/test_check_stac_metadata.py
refactored this test to call main, as it doesn't make sense to call the entire state machine for this test
> refactor: change test to call main instead of state machine

- poetry.lock
- pyproject.toml
In preparation for installing more.
> chore: Update Python packages

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/enabler_story.md
- .github/ISSUE_TEMPLATE/user_story.md
Closes #233 
After discussion today about moving stories to this repository, I've created some issue templates.
> Update issue templates

- datalake/backend/endpoints/dataset_versions/create.py
- datalake/backend/tests/utils.py
> refactor: Use `hex` property of UUID objects

- reset-dev-env.bash
This configuration takes a while to set up again, so we should make sure
to keep it.
> feat: Don't remove IDEA configuration

- backend/model.py
- infrastructure/storage_stack.py
Removes one level of indirection.
> refactor: Inline constant field values

- poetry.lock
To see if they fix https://github.com/linz/geospatial-data-lake/security/code-scanning/4?query=ref%3Arefs%2Fheads%2Fmaster and https://github.com/linz/geospatial-data-lake/security/code-scanning/6?query=ref%3Arefs%2Fheads%2Fmaster
> chore: Upgrade Python packages

- pyproject.toml
- tests/test_check_files_checksums.py
- tests/test_check_files_checksums_logging.py
- tests/test_check_stac_metadata.py
- tests/test_check_stac_metadata_logging.py
- tests/test_content_iterator.py
- tests/test_dataset_versions_endpoint.py
- tests/test_dataset_versions_endpoint_logging.py
- tests/test_datasets_endpoint.py
- tests/test_import_dataset.py
- tests/test_import_dataset_logging.py
- tests/test_processing_stack.py
- tests/test_storage_bucket.py
Closes https://github.com/linz/geospatial-data-lake/issues/334
> refactor: Use "should_" test name prefix

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- USAGE.md
- backend/dataset_versions/create.py
- backend/import_status/entrypoint.py
- backend/import_status/get.py
- backend/resources.py
- infrastructure/api_stack.py
- infrastructure/constructs/lambda_endpoint.py
- poetry.lock
- pyproject.toml
- reset-dev-env.bash
- response.json
- tests/aws_utils.py
- tests/general_generators.py
- tests/test_dataset_versions_endpoint.py
- tests/test_dataset_versions_endpoint_logging.py
- tests/test_import_status_endpoint.py
- tests/test_import_status_logging.py
- tests/test_processing_stack.py
Lambda endpoint to allow user to retrieve status update for Step Function and S3 batch Copy operation for their dataset.
> feat: Get Import Status

- backend/resources.py
- infrastructure/users_stack.py
Fixed Data Lake Users role name is needed to link role with Azure AD group configuration.
> feat(infra): fixed users role name

- .github/workflows/test.yml
- pyproject.toml
- tests/aws_utils.py
- tests/conftest.py
- tests/general_generators.py
- tests/test_check_stac_metadata.py
- tests/test_datasets_endpoint.py
- tests/test_import_dataset.py
- tests/test_import_dataset_logging.py
- tests/test_processing_stack.py
See https://github.com/pytest-dev/pytest-randomly/issues/327 for why we can't parallelise just yet.
> feat: Prep to run tests in parallel

- backend/dataset_versions/create.py
- backend/import_dataset/task.py
- backend/import_status/get.py
- tests/test_dataset_versions_endpoint_logging.py
- tests/test_import_dataset_logging.py
- tests/test_import_status_logging.py
Use the same name as in AWS Lambda: "event".
> refactor: Rename log key

- app.py
- backend/import_status/get.py
- infrastructure/api_stack.py
- infrastructure/processing_stack.py
- poetry.lock
- pyproject.toml
- tests/aws_utils.py
- tests/test_import_status_endpoint.py
- tests/test_import_status_logging.py
- tests/test_processing_stack.py
Added support for returning validation results to the end user
> feat: get import validation status

- clear-s3-buckets.bash
Use with extreme caution if you have access to any production buckets!
Based on <https://gist.github.com/weavenet/f40b09847ac17dd99d16>.
> feat: Add script to clear S3 buckets

- backend/datasets/create.py
- backend/datasets/get.py
- backend/datasets/update.py
- infrastructure/constructs/bundled_lambda_function.py
- infrastructure/constructs/lambda_endpoint.py
> refactor: Remove unnecessary f-strings

- infrastructure/api_stack.py
- infrastructure/constructs/batch_job_queue.py
- infrastructure/constructs/batch_submit_job_task.py
- infrastructure/constructs/bundled_lambda_function.py
- infrastructure/constructs/lambda_endpoint.py
- infrastructure/constructs/lambda_task.py
- infrastructure/constructs/table.py
- infrastructure/constructs/task_job_definition.py
- infrastructure/networking_stack.py
- infrastructure/processing_stack.py
- infrastructure/staging_stack.py
- infrastructure/storage_stack.py
- infrastructure/users_stack.py
> refactor: Don't import both core and core.*

- backend/check_stac_metadata/utils.py
- tests/test_check_stac_metadata.py
- tests/test_check_stac_metadata_logging.py
- tests/test_processing_stack.py
Closes https://github.com/linz/geospatial-data-lake/issues/391.
> fix: Use "assets" property instead of "item_assets"

- pyproject.toml
The TOML formatter no longer borks dependencies.
> refactor: Simplify pyproject.toml

- app.py
- backend/dataset_versions/create.py
- backend/import_dataset/task.py
- backend/parameter_store.py
- backend/resources.py
- infrastructure/processing_stack.py
- infrastructure/staging_stack.py
- infrastructure/storage_stack.py
- tests/test_check_stac_metadata.py
- tests/test_import_dataset.py
- tests/test_processing_stack.py
- tests/test_storage_bucket.py
> feat: Auto generate AWS resource names prep

- backend/parameter_store.py
- tests/test_parameter_store.py
The original error message doesn't contain the parameter name.
> feat: Log missing parameters

- backend/import_dataset/task.py
- backend/parameter_store.py
- infrastructure/storage_stack.py
- tests/test_check_stac_metadata.py
- tests/test_import_dataset.py
- tests/test_processing_stack.py
- tests/test_storage_bucket.py
It's a trivial string concatenation, rather than adding another SSM
parameter.
> refactor: Generate storage bucket ARN from name

- .dockerignore
> ci: Exclude more files from CDK

- backend/check.py
- backend/check_files_checksums/task.py
- backend/check_files_checksums/utils.py
- backend/check_stac_metadata/task.py
- backend/check_stac_metadata/utils.py
- tests/test_check_files_checksums.py
- tests/test_check_files_checksums_logging.py
- tests/test_check_stac_metadata.py
> feat: implement validation handling for incorrect staging bucket access

- backend/dataset_model.py
- backend/datasets/create.py
- backend/datasets/get.py
- backend/datasets/update.py
> fix: Typo in datasets title index name

- backend/resources.py
> chore: Remove unused enum entry

- tests/aws_utils.py
- tests/test_import_dataset.py
- tests/test_processing_stack.py
> test: Pull out constants

- USAGE.md
- app.py
- infrastructure/processing_stack.py
> fix: give s3 batch copy role correct permissions

- tests/test_processing_stack.py
> test: Add more details if execution output is missing

- tests/test_import_dataset.py
- tests/test_processing_stack.py
> refactor: Remove unnecessary nesting

- tests/test_import_dataset.py
- tests/test_processing_stack.py
> test: Unconditionally delete resources

- backend/check.py
- backend/check_stac_metadata/task.py
- backend/check_stac_metadata/utils.py
- tests/test_check_stac_metadata.py
> feat: Add user validation for non S3 URL and multiple directories

- tests/test_import_dataset.py
> refactor: Simplify import dataset test

- infrastructure/constructs/table.py
https://github.com/linz/geospatial-data-lake/issues/449
> fix: changed dynamodb billing model to pay per request

- backend/resources.py
- infrastructure/api_stack.py
- infrastructure/constructs/lambda_endpoint.py
> refactor: remove underscores from endpoint names

- backend/import_dataset/task.py
- backend/import_status/get.py
- backend/parameter_store.py
- infrastructure/constructs/batch_job_queue.py
- infrastructure/constructs/batch_submit_job_task.py
- infrastructure/constructs/lambda_task.py
- infrastructure/processing_stack.py
- tests/test_import_dataset.py
- tests/test_import_status_endpoint.py
- tests/test_processing_stack.py
> refactor: Strip file prefixes when copying prep

- backend/Dockerfile
[Relevant diff](https://github.com/python-poetry/poetry/commit/34d66baa24875bbf799276a8509743cf595ab662#diff-952871ed95a893e0348aa1269bf15e689d18756657cfec5c7316d05e55eb6dc6)
> feat: Use latest Poetry installer

- backend/check_stac_metadata/utils.py
- tests/test_check_files_checksums.py
- tests/test_check_stac_metadata.py
- tests/test_processing_stack.py
https://github.com/linz/geospatial-data-lake/issues/453
> feat: validate all same directory checks at once

- backend/import_dataset/task.py
- tests/test_import_dataset.py
- tests/test_processing_stack.py
Closes https://github.com/linz/geospatial-data-lake/issues/452
> fix: Strip file prefixes when copying

- backend/content_iterator/task.py
- tests/aws_utils.py
- tests/test_content_iterator.py
https://github.com/linz/geospatial-data-lake/issues/465
> feat: increase batch array size to maximum amount

- USAGE.md
- backend/import_dataset/task.py
- tests/test_import_dataset.py
- tests/test_import_dataset_logging.py
> refactor: Misc

- .github/ISSUE_TEMPLATE/bug_report.md
> docs: Cleanup bug report template

- USAGE.md
Updated Authentication and Authorization instructions and little reordering of content
> docs: USAGE file cleanup

- app.py
- backend/dataset_versions/create.py
- backend/datasets/create.py
- backend/datasets/delete.py
- backend/datasets/get.py
- backend/datasets/list.py
- backend/datasets/update.py
- backend/datasets_model.py
- backend/parameter_store.py
- backend/resources.py
- infrastructure/api_stack.py
- infrastructure/storage_stack.py
- tests/aws_utils.py
- tests/test_dataset_versions_endpoint_logging.py
> feat: Parameterise datasets table name

- infrastructure/constructs/table.py
Closes https://github.com/linz/geospatial-data-lake/issues/325, https://github.com/linz/geospatial-data-lake/issues/220, https://github.com/linz/geospatial-data-lake/issues/182.
- https://github.com/pynamodb/PynamoDB/issues/922
- https://stackoverflow.com/q/66699828/96588
- https://stackoverflow.com/q/66759449/96588
- https://github.com/aws/aws-cdk/issues/10952
> feat: Auto generate AWS resource names

- .gitmodules
- backend/check_stac_metadata/stac_validators.py
- backend/check_stac_metadata/utils.py
- infrastructure/constructs/task_job_definition.py
- tests/aws_utils.py
- tests/stac_objects.py
- tests/test_check_stac_metadata.py
- tests/test_check_stac_metadata_utils_logging.py
- tests/test_import_dataset.py
- tests/test_processing_stack.py
https://github.com/linz/geospatial-data-lake/issues/336
> feat: support catalog and item metadata

- poetry.lock
- pyproject.toml
> refactor: Remove smart-open dev dependency

- USAGE.md
- backend/check_stac_metadata/utils.py
- tests/test_check_stac_metadata.py
Closes https://github.com/linz/geospatial-data-lake/issues/359.
> feat: Allow relative paths in metadata

- package.json
> chore: Use latest aws-azure-login version

- package-lock.json
Also updates 'netmask' past CVE-2021-28918.
- https://github.com/sportradar/aws-azure-login/issues/179
> chore: Update aws-azure-login package

- backend/check.py
> chore: Remove unused enum value

- backend/check.py
- backend/check_stac_metadata/utils.py
- tests/test_check_stac_metadata.py
Closes https://github.com/linz/geospatial-data-lake/issues/446.
> feat: Report invalid json

- USAGE.md
- backend/datasets/create.py
- backend/datasets/get.py
- backend/datasets/update.py
- backend/datasets_model.py
- infrastructure/storage_stack.py
- pyproject.toml
- tests/aws_utils.py
- tests/stac_generators.py
- tests/test_datasets_endpoint.py
Closes https://github.com/linz/geospatial-data-lake/issues/522.
> feat: Remove owning group dataset parameter

- backend/api_responses.py
- backend/dataset_versions/create.py
- backend/datasets/create.py
- backend/datasets/delete.py
- backend/datasets/get.py
- backend/datasets/list.py
- backend/datasets/update.py
- backend/import_status/get.py
- tests/test_api_endpoint_handler.py
- tests/test_dataset_versions_endpoint.py
- tests/test_datasets_endpoint.py
- tests/test_import_status_endpoint.py
- tests/test_processing_stack.py
> refactor: Use constants for HTTP response codes

- backend/check_stac_metadata/utils.py
- tests/stac_objects.py
- tests/test_check_stac_metadata.py
- tests/test_check_stac_metadata_utils_logging.py
- tests/test_import_dataset.py
- tests/test_processing_stack.py
See
<https://github.com/stac-extensions/file/tree/a71fffebe01c713a167a90fbd6c1790d3adc1b96#checksums>.
Closes https://github.com/linz/geospatial-data-lake/issues/531.
> fix: Use new checksum property name

- .github/workflows/deploy.yml
> ci: production AWS stack upgrade testing before deployment

- USAGE.md
- backend/resources.py
- infrastructure/constructs/lambda_endpoint.py
- tests/test_datasets_endpoint.py
- tests/test_processing_stack.py
> docs: Simplify usage

- .github/workflows/deploy.yml
> ci: allow production deployment only from release branch

- backend/import_status/get.py
- tests/aws_utils.py
- tests/test_import_status_endpoint.py
- tests/test_import_status_logging.py
> refactor: Make import status messages more meaningful prep

- backend/import_status/get.py
- tests/test_import_status_endpoint.py
- tests/test_processing_stack.py
Based on https://github.com/linz/geospatial-data-lake/pull/540
Closes https://github.com/linz/geospatial-data-lake/issues/539.
> feat: Make import status messages more meaningful

- backend/datasets/delete.py
- tests/test_datasets_endpoint.py
Closes https://github.com/linz/geospatial-data-lake/issues/43.
> feat: Only allow deleting empty dataset

- pyproject.toml
> fix: Add Mitchell Paff to authors list

- .pre-commit-config.yaml
Closes https://github.com/linz/geospatial-data-lake/issues/578.
> fix: Lock hadolint version

- app.py
- infrastructure/api_stack.py
- tests/test_datasets_endpoint.py
Closes https://github.com/linz/geospatial-data-lake/issues/567.
> fix: Grant access to parameter needed for dataset deletion

- app.py
- infrastructure/processing_stack.py
- infrastructure/storage_stack.py
For easier redeploy of the processing stack.
Closes https://github.com/linz/geospatial-data-lake/issues/573.
> refactor: Move validation results table to storage stack

- infrastructure/networking_stack.py
- infrastructure/processing_stack.py
> refactor: Demote fields to variables

- backend/check_files_checksums/task.py
- backend/check_files_checksums/utils.py
- backend/check_stac_metadata/task.py
- backend/content_iterator/task.py
- backend/processing_assets_model.py
- backend/validation_results_model.py
- infrastructure/processing_stack.py
- tests/aws_utils.py
- tests/test_check_files_checksums.py
- tests/test_check_files_checksums_logging.py
- tests/test_check_stac_metadata.py
- tests/test_content_iterator.py
> fix: ssm throttling issues

- .github/dependabot.yml
- app.py
- backend/bundle.bash
- infrastructure/api_stack.py
- infrastructure/constructs/bundled_lambda_function.py
- infrastructure/constructs/import_file_function.py
- infrastructure/constructs/lambda_endpoint.py
- infrastructure/constructs/lambda_task.py
- infrastructure/lambda_layers/botocore/poetry.lock
- infrastructure/lambda_layers/botocore/pyproject.toml
- infrastructure/lambda_layers_stack.py
- infrastructure/processing_stack.py
- poetry.lock
- pyproject.toml
This should speed up deployment by only installing the big botocore
package once.
Closes https://github.com/linz/geospatial-data-lake/issues/194.
> refactor: Add botocore Lambda layer

- LICENSE
> chore: Update license date

- .github/workflows/deploy.yml
- .pre-commit-config.yaml
See
<https://github.com/macisamuele/language-formatters-pre-commit-hooks/issues/53#issuecomment-823596065>.
> feat: Reintroduce YAML formatter

- .github/workflows/update-license-year.yml
As [suggested](https://github.com/linz/geospatial-data-lake/pull/597#issuecomment-823644624).
> feat: Update license date automatically

- README.md
Closes https://github.com/linz/geospatial-data-lake/issues/357.
> docs: Document vulnerability notification setup

- .github/dependabot.yml
> fix: Scan Dockerfile in backend directory

- infrastructure/constructs/bundled_code.py
- infrastructure/constructs/bundled_lambda_function.py
- infrastructure/constructs/lambda_endpoint.py
Closes https://github.com/linz/geospatial-data-lake/issues/605.
> refactor: De-duplicate bundled Lambda code generation

- README.md
- app.py
- cdk.json
- infrastructure/api_stack.py
- infrastructure/lds.py
- infrastructure/roles.py
Related to https://github.com/linz/geospatial-data-lake/issues/496.
> feat: Add Koordinates storage access role

- backend/datasets_model.py
> refactor: Remove default null values

- backend/datasets_model.py
- tests/test_datasets_model_base.py
Closes https://github.com/linz/geospatial-data-lake/issues/244.
> fix: Generate unique IDs per dataset

- infrastructure/lds.py
> chore: Remove redundant role name suffix

- backend/datasets_model.py
- poetry.lock
- pyproject.toml
- tests/test_datasets_endpoint.py
Shorter and more user friendly than UUIDs.
> feat: Use ULIDs for dataset IDs

- backend/clock.py
- backend/datasets_model.py
> fix: Use defaults as documented

- .github/workflows/deploy.yml
This way we can ensure that anything merged to master (except manual
merges) will be deployment tested before merging.
> feat: Deploy pull requests labeled "automerge"

- .github/workflows/deploy.yml
Not just when labelling the PR, but also when pushing to an already
labelled PR.
> fix: Run deployment test on automerge pull requests

- tests/aws_utils.py
- tests/test_dataset_versions_endpoint.py
- tests/test_dataset_versions_endpoint_logging.py
- tests/test_datasets_endpoint.py
- tests/test_processing_stack.py
> refactor: Use implicitly generated dataset ID

- backend/datasets_model.py
- poetry.lock
- pyproject.toml
- tests/test_datasets_endpoint.py
Closes https://github.com/linz/geospatial-data-lake/issues/609.
> feat: Make ULID timestamp readable

- app.py
- backend/import_dataset/task.py
- infrastructure/processing_stack.py
- poetry.lock
- pyproject.toml
- tests/test_import_dataset.py
- tests/test_import_dataset_logging.py
- tests/test_processing_stack.py
Closes https://github.com/linz/geospatial-data-lake/issues/609.
> feat: Add dataset title to S3 key

- .github/pull_request_template.md
Workaround for the link pointing to
<https://github.com/linz/geospatial-data-lake/pull/CODING.md#Code-review-checklist>,
based on <https://stackoverflow.com/q/49242645/96588>.
**This is the link I've fixed in this PR:** [Code review checklist](/linz/geospatial-data-lake/blob/master/CODING.md#Code-review-checklist)
> docs: Fix code review checklist URL

- backend/resources.py
- infrastructure/api_stack.py
> feat: added read only role for all linz users

- tests/test_dataset_versions_endpoint.py
- tests/test_datasets_endpoint.py
- tests/test_processing_stack.py
> tests: Use constant status codes

- backend/dataset_versions/create.py
- tests/test_dataset_versions_endpoint.py
Based on https://github.com/linz/geospatial-data-lake/pull/660
Closes https://github.com/linz/geospatial-data-lake/issues/610.
> feat: Change dataset version to ULID

- .gitignore
- cdk.context.json
As per
<https://aws.amazon.com/blogs/devops/best-practices-for-developing-cloud-applications-with-aws-cdk/>.
This partially reverts commit e118a393626e7436a11257ea2a91f445c3b3a36a.
> feat: Track generated CDK context

- infrastructure/constructs/backend.py
- infrastructure/constructs/bundled_code.py
- infrastructure/constructs/bundled_lambda_function.py
- infrastructure/constructs/lambda_endpoint.py
- infrastructure/constructs/task_job_definition.py
> refactor: Pull out backend directory name

- tests/test_dataset_versions_endpoint.py
- tests/test_dataset_versions_endpoint_logging.py
- tests/test_import_dataset_logging.py
> refactor: Avoid unused test arguments

- backend/import_dataset/task.py
This way we'll know if any of the literals are no longer valid.
> refactor: Type annotate AWS API literals

- infrastructure/api_stack.py
- infrastructure/lambda_layers_stack.py
- infrastructure/lds_stack.py
- infrastructure/networking_stack.py
- infrastructure/processing_stack.py
- infrastructure/staging_stack.py
- infrastructure/storage_stack.py
> refactor: removed kwargs argument from stacks

- .github/workflows/deploy.yml
- .github/workflows/prod-upgrade-deploy-test.yml
- README.md
> fix: add retain policy to prod and removing from CI

- backend/api_responses.py
- backend/dataset_versions/create.py
- backend/datasets/create.py
- backend/datasets/delete.py
- backend/datasets/get.py
- backend/datasets/update.py
- backend/import_status/get.py
- backend/step_function_event_keys.py
- tests/test_dataset_versions_endpoint.py
- tests/test_dataset_versions_endpoint_logging.py
- tests/test_import_status_endpoint.py
- tests/test_import_status_logging.py
- tests/test_processing_stack.py
> refactor: Pull out execution ARN key constant

- infrastructure/api_stack.py
- infrastructure/constructs/lambda_endpoint.py
- infrastructure/processing_stack.py
> refactor: Simplify parameter access

- infrastructure/constructs/lambda_task.py
- infrastructure/processing_stack.py
> refactor: Change `LambdaTask` to a `LambdaInvoke` subclass

- infrastructure/api_stack.py
- infrastructure/networking_stack.py
- infrastructure/processing_stack.py
> chore: remove useless docstrings

- backend/resources.py
- infrastructure/api_stack.py
> refactor(infra): rename S3 and API user roles

- backend/api_keys.py
- backend/api_responses.py
- backend/check_files_checksums/utils.py
- backend/check_stac_metadata/utils.py
- backend/content_iterator/task.py
- backend/import_status/get.py
- backend/validation_summary/task.py
- infrastructure/constructs/processing.py
- tests/test_api_endpoint_handler.py
- tests/test_check_files_checksums.py
- tests/test_check_files_checksums_logging.py
- tests/test_check_stac_metadata.py
- tests/test_check_stac_metadata_utils_logging.py
- tests/test_content_iterator.py
- tests/test_dataset_versions_endpoint.py
- tests/test_dataset_versions_endpoint_logging.py
- tests/test_datasets_endpoint.py
- tests/test_import_dataset_logging.py
- tests/test_import_status_endpoint.py
- tests/test_import_status_logging.py
- tests/test_processing_stack.py
- tests/test_validation_summary.py
- tests/test_validation_summary_logging.py
> refactor: Pull out API key constants

- .github/pull_request_template.md
- .github/workflows/deploy.yml
- CODING.md
- README.md
- USAGE.md
- app.py
- backend/resources.py
- cdk.context.json
- infrastructure/constructs/api.py
- infrastructure/constructs/batch_job_queue.py
- infrastructure/constructs/storage.py
- infrastructure/networking_stack.py
- pyproject.toml
- reset-dev-env.bash
- tests/test_datasets_endpoint.py
- tests/test_processing_stack.py
- tests/test_storage_bucket.py
> refactor: rename product to Geostore

- backend/check_stac_metadata/task.py
- backend/content_iterator/task.py
- backend/dataset_versions/create.py
- backend/import_dataset/task.py
- backend/import_status/get.py
- backend/step_function.py
- backend/step_function_event_keys.py
- backend/upload_status/task.py
- backend/validation_summary/task.py
- infrastructure/constructs/api.py
- infrastructure/constructs/processing.py
- infrastructure/constructs/s3_policy.py
- poetry.lock
- pyproject.toml
- tests/aws_utils.py
- tests/test_check_stac_metadata.py
- tests/test_check_stac_metadata_task_logging.py
- tests/test_content_iterator.py
- tests/test_import_dataset.py
- tests/test_import_dataset_logging.py
- tests/test_import_status_endpoint.py
- tests/test_import_status_logging.py
- tests/test_processing_stack.py
- tests/test_step_function_logging.py
- tests/test_upload_status.py
- tests/test_upload_status_logging.py
- tests/test_validation_summary.py
- tests/test_validation_summary_logging.py
Closes https://github.com/linz/geospatial-data-lake/issues/673.
> feat: Make copy jobs synchronous

- backend/datasets_model.py
- tests/test_datasets_endpoint.py
Closes https://github.com/linz/geospatial-data-lake/issues/703.
> feat: Shorten dataset datetime format

- USAGE.md
Two of the properties have changed name since the original documentation
was written.
> docs: Fix STAC documentation

- .github/dependabot.yml
> fix: Correct botocore dependabot path

- README.md
Closes https://github.com/linz/geostore/issues/718.
> feat: Add badges

- USAGE.md
Closes https://github.com/linz/geostore/issues/611.
> docs: Manage renaming datasets

- backend/check_stac_metadata/utils.py
- pyproject.toml
- tests/test_check_files_checksums.py
- tests/test_check_files_checksums_logging.py
- tests/test_check_stac_metadata_task_logging.py
- tests/test_parameter_store.py
> tests: Prep for 100% coverage

- .github/workflows/test.yml
- .gitignore
- README.md
- backend/check_stac_metadata/task.py
- backend/datasets/entrypoint.py
- backend/datasets/get.py
- backend/datasets_model.py
- backend/import_dataset/task.py
- backend/import_dataset_file.py
- backend/import_metadata_file/task.py
- backend/pystac_io_methods.py
- backend/validation_results_model.py
- pyproject.toml
- tests/aws_utils.py
- tests/test_datasets_endpoint.py
- tests/test_import_asset_file.py
- tests/test_import_dataset_file.py
- tests/test_import_metadata_file.py
Closes https://github.com/linz/geostore/issues/731.
> tests: 100% coverage

- .pre-commit-config.yaml
I've specified a commit ID rather than a tag for security reasons - if
anyone manages to replace the tag with some malicious code we won't be
affected.
> feat: Use latest Prettier release

- USAGE.md
> docs: updated dataset endpoint documentation

- .github/workflows/deploy.yml
Also put the GitHub repository check first, since it's usually the most
important one.
> fix: Group boolean operators properly

- .github/workflows/deploy.yml
Closes https://github.com/linz/geostore/issues/761.
> fix: Bootstrap CDK before deploying

- .github/workflows/test.yml
Avoids constructing stacks with warnings. Useful to catch issues early.
> feat: Use strict CDK deployment option

- backend/Dockerfile
> chore: Bump Poetry installer signature

- .github/workflows/deploy.yml
This partially reverts commit 4dab11e793e1833a7174837b8e8bb50818ea0b44.
> feat: Run deployment when pushing release tags

- backend/resources.py
Someone else has already used the "geostore" name.
> fix: Use LINZ-specific bucket names

- .github/workflows/prod-upgrade-deploy-test.yml
> fix: Add force flag to bootstrap on upgrade to allow copy of prod

- .github/workflows/deploy.yml
- .github/workflows/prod-upgrade-deploy-test.yml
- .github/workflows/test.yml
> fix: Add changeset name to avoid parallel cdk deployment errors

- backend/populate_catalog/task.py
> Update root catalog description and title

- infrastructure/constructs/api.py
- infrastructure/constructs/import_file_function.py
- tests/aws_utils.py
> refactor: Reverse role assumption for S3 copy prep

- tests/test_processing_stack.py
- tests/test_storage_bucket.py
Since the relevant resource names are no longer dynamic, we might as
well just reference them directly.
> refactor: Remove unnecessary test classes

- backend/dataset_versions/create.py
- backend/import_status/get.py
- backend/log.py
- backend/step_function.py
- infrastructure/constructs/removal_policy.py
- tests/aws_utils.py
- tests/conftest.py
- tests/general_generators.py
- tests/test_check_files_checksums.py
- tests/test_check_files_checksums_logging.py
- tests/test_check_stac_metadata_task_logging.py
- tests/test_check_stac_metadata_utils_logging.py
- tests/test_dataset_versions_endpoint.py
- tests/test_dataset_versions_endpoint_logging.py
- tests/test_datasets_endpoint.py
- tests/test_import_dataset_file.py
- tests/test_import_dataset_logging.py
- tests/test_import_status_endpoint.py
- tests/test_import_status_logging.py
- tests/test_processing_stack.py
- tests/test_step_function_logging.py
Built on https://github.com/linz/geostore/pull/807
> refactor: Import built in properties directly

- backend/import_asset_file/task.py
- backend/import_dataset/task.py
- backend/import_dataset_file.py
- backend/step_function.py
- backend/update_dataset_catalog/task.py
> refactor: Simplify type checking imports

- README.md
- pyproject.toml
- tests/aws_utils.py
> tests: Verify branch coverage

- backend/import_dataset_file.py
- tests/test_import_dataset_file.py
> feat: Log dataset file import result

- poetry.lock
- pyproject.toml
> tests: Add stub packages

- README.md
> docs: Explain how to set up dev env script crontab entry

- .github/workflows/codeql-analysis.yml
As recommended
<https://github.com/linz/geostore/actions/runs/955571447>:
> Please make sure that every branch in on.pull_request is also in
> on.push so that Code Scanning can compare pull requests against the
> state of the base branch.
> feat: Run CodeQL analysis on all pushes

- README.md
> docs: Add lgtm.com badges

- .github/workflows/prod-upgrade-deploy-test.yml
> refactor: Use checkout GitHub action rather than command

- .github/workflows/cdk-bootstrap.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/prod-upgrade-deploy-test.yml
- .github/workflows/test.yml
- README.md
- reset-dev-env.bash
> feat: Use repo interpreter versions in pipelines

- backend/resources.py
- infrastructure/constructs/notify.py
> fix: add unique cloudwatch rule names

- backend/dataset_versions/create.py
- backend/upload_status/task.py
- backend/validation_summary/task.py
- tests/test_check_stac_metadata_task_logging.py
- tests/test_dataset_versions_endpoint_logging.py
- tests/test_import_status_logging.py
- tests/test_upload_status_logging.py
- tests/test_validation_summary_logging.py
> fix: replace event strings with key constant

- USAGE.md
> fix: Use correct role assumption policy format

- backend/check_stac_metadata/stac_validators.py
- backend/datasets_model.py
- backend/notify_status_update/task.py
- backend/populate_catalog/task.py
- backend/validation_results_model.py
- setup.cfg
- tests/test_api_endpoint_handler.py
- tests/test_upload_status.py
- tests/test_validation_summary_logging.py
Simplifies the configuration while probably not needing any future
changes.
> feat: Use strict mypy configuration

- poetry.lock
- pyproject.toml
> fix: add pynamodb to notify slack package

- backend/bundle.bash
- reset-dev-env.bash
> feat: Improve script error checking

- infrastructure/constructs/notify.py
> fix: bad indent in infrastructure code

- CODING.md
- USAGE.md
> docs: Create developer docs for testing dataset import

- pyproject.toml
The "black" profile corresponds to most of the other settings we're
using.
> refactor: Simplify isort configuration

- backend/notify_status_update/task.py
- tests/test_notify_slack.py
> fix: Truncate slack message blocks to fit within limit

- README.md
- USAGE.md
> docs: Document Python version upgrade

- USAGE.md
> docs: Add further user documentation for SNS message filtering

- backend/check_stac_metadata/utils.py
- backend/datasets_model.py
> refactor: Don't refer to magic number for a prefix check

- backend/check_stac_metadata/utils.py
- tests/test_check_stac_metadata.py
- tests/test_import_dataset.py
Closes https://github.com/linz/geostore/issues/892
> fix: Treat explicitly and implicitly relative paths the same

- backend/import_asset_file/task.py
- tests/test_import_dataset.py
Closes https://github.com/linz/geostore/issues/892
> fix: Actually write asset contents

- poetry.lock
- pyproject.toml
> feat: Use same Poetry Python restriction as Pyenv

- backend/boto3_config.py
- backend/dataset_versions/create.py
- backend/datasets/delete.py
- backend/import_asset_file/task.py
- backend/import_dataset/task.py
- backend/import_metadata_file/task.py
- backend/notify_status_update/task.py
- backend/parameter_store.py
- backend/populate_catalog/task.py
- backend/pystac_io_methods.py
- backend/s3.py
- backend/step_function.py
- backend/sts.py
- tests/aws_utils.py
- tests/conftest.py
Closes https://github.com/linz/geostore/issues/893
-->
> feat: use boto3 standard retry mode

- README.md
There should be only one H1 on a page.
> docs: Fix readme headings

- .github/workflows/test.yml
- README.md
- pyproject.toml
By putting the test directory into the configuration, we don't have to
explicitly list them in each `pytest` call.
> feat: Simplify pytest commands

- tests/test_import_dataset.py
- tests/test_populate_catalog.py
- tests/test_processing_stack.py
> tests: Verify imported metadata and asset contents prep

- tests/test_import_dataset.py
- tests/test_processing_stack.py
> tests: Verify imported metadata and asset contents

- backend/Dockerfile
This should get the pipelines going again.
> fix: Get Poetry working after updates

- backend/Dockerfile
> chore: Bump Poetry installer checksum

- .github/workflows/cdk-bootstrap.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/prod-upgrade-deploy-test.yml
- .github/workflows/test.yml
- backend/Dockerfile
- reset-dev-env.bash
> chore: Don't install superfluous Python packages

- .gitmodules
- README.md
> feat: Validate LINZ extension prep

- backend/check_files_checksums/task.py
- backend/check_stac_metadata/task.py
- backend/step_function.py
- tests/dynamodb_generators.py
- tests/test_check_files_checksums.py
- tests/test_check_stac_metadata.py
- tests/test_check_stac_metadata_utils_logging.py
- tests/test_content_iterator.py
> refactor: Pull out method to create hash key

- .github/workflows/test.yml
> refactor: Use idiomatic way to pass configuration

- backend/check.py
- backend/check_stac_metadata/utils.py
- tests/test_check_stac_metadata.py
Closes https://github.com/linz/geostore/issues/329
> fix: Propagate error message to end user

- .gitmodules
> feat: Specify submodule branches

- .run/pytest in geostore.run.xml
> feat: Set up basic IDEA Pytest runner configuration

- pyproject.toml
> docs: Add some standard Poetry package metadata

- geostore/populate_catalog/task.py
- tests/test_datasets_endpoint.py
- tests/test_populate_catalog.py
> refactor: Rename constant for clarity

- geostore/check_stac_metadata/stac_validators.py
- tests/stac_objects.py
> refactor: Pull out reused paths

- pyproject.toml
> test: Exclude Nix store from coverage

- USAGE.md
- geostore/cli.py
- pyproject.toml
- tests/aws_utils.py
- tests/test_cli.py
> feat: Get dataset version status via CLI

- USAGE.md
- [It's not easy to get the app version from a single place](https://github.com/python-poetry/poetry/issues/273)
> docs: Merge CLI and API docs

- geostore/cli.py
- poetry.lock
- pyproject.toml
- tests/test_cli.py
Contributes to https://github.com/linz/geostore/issues/1146.
> feat: Add CLI --version flag

- geostore/Dockerfile
> feat: Upgrade Poetry installer

- shell.nix
> feat: Allow overriding pkgs

- .github/workflows/mutation-test.yml
The [action](https://github.com/marketplace/actions/junit-report-action) seems to be meant to be used on a PR build, so I'm not sure whether it'll show up on a main branch build. Probably?
> feat: Publish mutmut report

- shell.nix
> feat: Upgrade Nix shell to 21.11

- geostore/resources.py
- infrastructure/constructs/api.py
- poetry.lock
- pyproject.toml
<!-- List of links to issues which will be closed by this PR. Uncomment this section if relevant.
Closes https://github.com/linz/geostore/issues/1223
> feat: log api user details

- .envrc
- README.md
- activate-dev-env.bash
- shell.nix
This should ensure that the Nix shell derivations aren't garbage collected.
> feat: Enable lorri

- geostore/check_files_checksums/task.py
- geostore/check_files_checksums/utils.py
- geostore/check_stac_metadata/task.py
- geostore/check_stac_metadata/utils.py
- geostore/dataset_versions/create.py
- geostore/datasets/entrypoint.py
- geostore/import_dataset/task.py
- geostore/import_dataset_file.py
- geostore/import_status/get.py
- geostore/notify_status_update/task.py
- geostore/parameter_store.py
- geostore/populate_catalog/task.py
- geostore/step_function.py
- geostore/update_dataset_catalog/task.py
- geostore/upload_status/task.py
- geostore/validation_summary/task.py
- tests/test_check_files_checksums.py
- tests/test_check_files_checksums_logging.py
- tests/test_check_stac_metadata.py
- tests/test_check_stac_metadata_task_logging.py
- tests/test_check_stac_metadata_utils_logging.py
- tests/test_dataset_versions_endpoint_logging.py
- tests/test_import_dataset_file.py
- tests/test_import_dataset_logging.py
- tests/test_import_status_logging.py
- tests/test_notify_slack.py
- tests/test_parameter_store.py
- tests/test_step_function_logging.py
- tests/test_upload_status_logging.py
- tests/test_validation_summary_logging.py
> refactor: Declare loggers as such

- tests/test_check_files_checksums.py
The value doesn't matter here. This prepares the code for mypy 0.930.
> fix: Match argument type to method signature

- geostore/datasets_model.py
- geostore/validation_results_model.py
> chore: Remove obsolete Pylint override

- .pre-commit-config.yaml
> fix: Run nixpkgs-fmt only at commit stage

- cdk.context.json
> chore: Bump CDK context

- reset-dev-env.bash
> chore: Undo CDK workaround

- .github/workflows/build.yml
- .github/workflows/cdk-bootstrap.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/mutation-test.yml
- .github/workflows/prod-upgrade-deploy-test.yml
- .github/workflows/test.yml
- .github/workflows/update-license-year.yml
> chore: Bump checkout action version

- infrastructure/constructs/import_file_function.py
- infrastructure/constructs/lambda_task.py
- infrastructure/constructs/notify.py
- infrastructure/constructs/processing.py
Hyphens are removed from the construct ID when creating the logical ID,
but case is kept.
> refactor: Use CamelCase for Lambda names

- .pre-commit-config.yaml
This seems to be much faster.
See
<https://github.com/pre-commit/mirrors-mypy/blob/f6f816c65d285f8a4a15e0e9965b3dd66ecddd79/.pre-commit-hooks.yaml>.
> feat: Update mypy pre-commit setup from source

- infrastructure/constructs/bundled_lambda_function.py
- infrastructure/constructs/import_file_function.py
- infrastructure/constructs/lambda_config.py
- infrastructure/constructs/lambda_endpoint.py
- infrastructure/constructs/processing.py
> fix: Bump Lambda resources

- shell.nix
Removes the need for all of the current overrides.
> chore: Bump nixpkgs

- shell.nix
> fix: Use single Python interpreter

- geostore/environment.py
- geostore/resources.py
- infrastructure/constructs/batch_job_queue.py
- infrastructure/constructs/lds.py
- infrastructure/constructs/task_job_definition.py
- infrastructure/networking_stack.py
- tests/test_cli.py
To avoid duplicating this logic all over the place.
> refactor: Pull out `is_production` function

- .github/workflows/test.yml
- app.py
- geostore/resources.py
- infrastructure/constructs/api.py
- infrastructure/logging_stack.py
Based on <https://stackoverflow.com/a/71468129/96588>.
Closes https://github.com/linz/geostore/issues/1450.
> fix: Reuse CloudTrail trail between runs

- infrastructure/constructs/batch_submit_job_task.py
> refactor: Change field to local variable

- infrastructure/constructs/api.py
- infrastructure/constructs/batch_job_queue.py
- infrastructure/constructs/batch_submit_job_task.py
- infrastructure/constructs/bundled_lambda_function.py
- infrastructure/constructs/import_file_function.py
- infrastructure/constructs/lambda_endpoint.py
- infrastructure/constructs/lds.py
- infrastructure/constructs/notify.py
- infrastructure/constructs/opentopo.py
- infrastructure/constructs/processing.py
- infrastructure/constructs/staging.py
- infrastructure/constructs/storage.py
- infrastructure/constructs/task_job_definition.py
- infrastructure/networking_stack.py
- poetry.lock
> chore: Upgrade aws-cdk packages

- geostore/check_files_checksums/utils.py
- geostore/cli.py
- geostore/processing_assets_model.py
- geostore/validation_results_model.py
- tests/aws_utils.py
- tests/test_cli.py
Makes sure that refactors don't break call sites.
> refactor: Enforce named optional arguments

- tests/general_generators.py
- tests/stac_objects.py
- tests/test_processing_stack.py
> fix: multi asset processing test

- USAGE.md
- cdk.context.json
- infrastructure/application_stack.py
- infrastructure/constructs/api.py
> feat: allow api role to be assumed by anyone in LINZ organization

- geostore/check_stac_metadata/task.py
- tests/test_check_stac_metadata.py
- tests/test_check_stac_metadata_task_logging.py
> feat: allow partial dataset upload prep

- .editorconfig
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/enabler_story.md
- .github/ISSUE_TEMPLATE/user_story.md
- CODING.md
- README.md
- USAGE.md
Fixes nested Markdown lists, but triggers
<https://github.com/prettier/prettier/issues/5019>. Hopefully that's fixed
soon.
> feat: Add editor configuration

- .github/workflows/mutation-test.yml
It takes a long time, and is rarely inspected.
> chore: Don't run mutation testing on master push

- geostore/datasets_model.py
- geostore/step_function.py
- geostore/validation_results_model.py
- geostore/validation_summary/task.py
- infrastructure/constructs/api.py
- pyproject.toml
- tests/test_check_files_checksums.py
- tests/test_check_stac_metadata.py
- tests/test_check_stac_metadata_task_logging.py
- tests/test_check_stac_metadata_utils_logging.py
- tests/test_import_dataset_file.py
- tests/test_processing_stack.py
> chore: Remove useless pylint suppressions

- USAGE.md
Better documentation with examples to support #1585
> docs: add examples for assuming roles from LINZ accounts

- .github/workflows/cdk-bootstrap.yml
Necessary to merge branches with new major versions of CDK.
> feat: Enable bootstrapping CDK manually

- infrastructure/constructs/api.py
> refactor: remove s3 users role in order to move in stack

- geostore/check_files_checksums/task.py
- geostore/check_files_checksums/utils.py
- geostore/check_stac_metadata/task.py
- geostore/check_stac_metadata/utils.py
- geostore/s3_utils.py
- tests/aws_utils.py
- tests/test_check_files_checksums.py
- tests/test_check_stac_metadata.py
- tests/test_check_stac_metadata_task_logging.py
- tests/test_check_stac_metadata_utils_logging.py
- tests/test_s3_utils.py
> refactor: extract common get_s3_url_reader method

- CODING.md
- tests/test_check_stac_metadata_task_logging.py
- tests/test_populate_catalog.py
- tests/test_update_dataset_catalog.py
> refactor: Use relative imports in main directories

- geostore/check_files_checksums/utils.py
- geostore/check_stac_metadata/utils.py
- geostore/s3_utils.py
- tests/aws_utils.py
- tests/test_check_files_checksums.py
- tests/test_check_stac_metadata.py
- tests/test_check_stac_metadata_task_logging.py
- tests/test_check_stac_metadata_utils_logging.py
- tests/test_s3_utils.py
> feat: validate partial datasets prep 4

- USAGE.md
Should use the production roles rather than the nonprod roles in examples.
> docs: use prod roles in examples

- .github/workflows/test.yml
> refactor: Simplify expressions

- .github/workflows/test.yml
> fix: Run S3 cleanup when pipeline fails

- infrastructure/constructs/lambda_layers/botocore/.gitignore
CDK creates it during synthesize.
> chore: Ignore generated requirements.txt file

- geostore/import_metadata_file/task.py
- tests/test_import_metadata_file.py
- tests/test_processing_stack.py
In order to fix pystac issue https://github.com/stac-utils/pystac/issues/801
> fix: Remove absolute self URLs from STAC objects in Geostore

- .kodiak.toml
> feat: Auto-merge minor dependency updates

- shell.nix
> chore: Bump nixpkgs version to latest stable

- tests/test_check_stac_metadata.py
- tests/test_import_dataset.py
- tests/test_s3_utils.py
> refactor: Use STAC constants

- geostore/datasets_model.py
- geostore/update_root_catalog/task.py
- infrastructure/application_stack.py
- infrastructure/constructs/processing.py
- tests/aws_utils.py
- tests/test_update_dataset_catalog.py
> feat: track most recent dataset version

- CODING.md
- USAGE.md
Closes https://github.com/linz/geostore/issues/1733.
> docs: Fix role assumption description

- geostore/check_stac_metadata/utils.py
- geostore/processing_assets_model.py
- tests/aws_utils.py
- tests/test_check_stac_metadata.py
- tests/test_content_iterator.py
- tests/test_processing_stack.py
> feat: add new filename field to processing assets table

- geostore/check_files_checksums/task.py
- geostore/check_files_checksums/utils.py
- tests/test_check_files_checksums.py
> refactor: checksum code refactoring

- USAGE.md
- tests/test_processing_stack.py
> docs: Explain Python usage

- geostore/dataset_versions/create.py
- geostore/step_function_keys.py
- tests/test_check_files_checksums.py
- tests/test_check_files_checksums_logging.py
- tests/test_check_stac_metadata.py
- tests/test_check_stac_metadata_task_logging.py
> refactor: pull out Empty current dataset version field

- tests/aws_utils.py
- tests/test_check_files_checksums.py
- tests/test_import_dataset.py
- tests/test_processing_stack.py
> refactor: test db entries at lower level

- geostore/update_root_catalog/task.py
- infrastructure/constructs/bundled_lambda_function.py
- infrastructure/constructs/processing.py
- tests/conftest.py
- tests/test_populate_catalog.py
- tests/test_update_dataset_catalog.py
> fix: lambda concurrency issues

- .github/pull_request_template.md
- CODING.md
> docs: Add typical code review workflow

- CODING.md
> docs: Simplify pull request guidelines

- CODING.md
> docs: Recommend portable Markdown syntax

- .github/workflows/.env
- .github/workflows/cdk-bootstrap.yml
- .github/workflows/deploy.yml
- .github/workflows/mutation-test.yml
- .github/workflows/prod-upgrade-deploy-test.yml
- .github/workflows/test.yml
- infrastructure/application_stack.py
Draft PR needed to trigger workflow on GitHub actions. This is needed for testing.
> feat: Switching to OIDC connect

- .github/workflows/cdk-bootstrap.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/mutation-test.yml
- .github/workflows/package-cli.yml
- .github/workflows/prod-upgrade-deploy-test.yml
- .github/workflows/test.yml
- .github/workflows/update-license-year.yml
> fix: Use specific action versions

- tests/test_cli.py
> test: Include mismatching text in test output

- geostore/dataset_versions/create.py
- geostore/datasets_model.py
- poetry.lock
- pyproject.toml
- tests/test_cli.py
> feat: Use maintained ULID library

- .github/workflows/cdk-bootstrap.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/package-cli.yml
- .github/workflows/prod-upgrade-deploy-test.yml
- geostore/Dockerfile
> fix: Use new non-dev flag

- CODING.md
- README.md
- USAGE.md
- geostore/populate_catalog/task.py
- infrastructure/constructs/batch_job_queue.py
- poetry.lock
- pyproject.toml
- tests/test_check_stac_metadata.py
> docs: Use official organisation name

- README.md
> fix: Footnote syntax

- README.md
> docs: Release notes

- nixpkgs.json
See <https://github.com/nix-community/poetry2nix/issues/693#issuecomment-1291729903>.
> build: Bump nixpkgs to get flit-scm

- .pre-commit-config.yaml
- activate-dev-env.bash
- clear-s3-buckets.bash
- generate-requirements-files.bash
- geostore/bundle.bash
- reset-dev-env.bash
- shell.nix
> feat: Format shell scripts automatically

- bump-nixpkgs.bash
Avoids using a name dependent on when the script is run.
Also swap diff inputs. Shows the more natural diff with the original contents on the left and the new contents on the right.
> feat: Use commit date for nixpkgs.json name

- .envrc
- .pre-commit-config.yaml
> chore: Re-init lorri

- geostore/check_stac_metadata/stac_validators.py
- poetry.lock
- pyproject.toml
> refactor: Replace deprecated distutils with packaging

- infrastructure/constructs/processing.py
Step function logging is recommended by cdk nag. This is a useful feature to have; however, state machine logging requires a bespoke policy to be added to cloudwatch logs resource policy on each deployment (i.e. custom log group name). Our CI deployment setup meant that we exceed cloudwatch logs policy size fairly quickly. AWS recommends using vended logs for such implementation. Using a randomly generated log group name in non prod meant that we need to keep track of each log group and clean up after each ci run. This isn't a problem, but it isn't ideal in prod because the logs become difficult to find, and we end up with a large catalog of logs after some time. Setting up a static vended log group name is also problematic because AWS wouldn't deploy after the initial setup since the log …
> fix: Remove state machine logging

- poetry.lock
- pyproject.toml
> refactor: Change dev dependencies into new format

- poetry.lock
- pyproject.toml
> refactor: Specify dependency versions in pyproject.toml

- pyproject.toml
> chore: Exclude irrelevant files from package

- nixpkgs.json
- shell.nix
- [Blocked by python-ulid dependency](https://github.com/nix-community/poetry2nix/issues/921)
> build: Bump nixpkgs

- geostore/datasets_model.py
- geostore/import_dataset/task.py
- geostore/processing_assets_model.py
- geostore/s3_utils.py
- geostore/validation_results_model.py
- tests/aws_utils.py
> refactor: Avoid silencing "too few public methods"

- .github/workflows/prod-upgrade-deploy-test.yml
> refactor: Remove Python package install fallback

- .github/workflows/cdk-bootstrap.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/mutation-test.yml
- .github/workflows/prod-upgrade-deploy-test.yml
- .github/workflows/test.yml
- reset-dev-env.bash
With the new `--all-extras` flag.
> refactor: Simplify all extras install
