- .github/workflows/codeql-analysis.yml
codeql code analysis (closes #12)
This has been implemented in the same manner as basemaps which is pretty much the [src repos example](codeql) verbatim 
**Will only pass codeql analysis check if the repo is public** (repo was made public for the below test to pass. It is back as private awaiting for other tasks associated with epic #31 to be completed)
> ci: codeql code  analysis

- .github/workflows/ci.yml
This fixes problem when after CI failure AWS stack was not deleted and all subsequent CI jobs started to fail due duplicate AWS stack resources.
> ci: perform CI AWS stack cleanup after failure

- .github/workflows/ci.yml
see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
closes: #57
> ci: replace deprecated 'set-env' command with environment file

- .github/workflows/ci.yml
To prevent AWS resource names conflicts.
> ci: wait if another CI AWS stack already exists

- .github/workflows/ci.yml
- .github/workflows/wait-for-stack-teardown.bash
This should allow us to run multiple CI pipelines in parallel.
> ci: Wait for stack teardown before deploying

- .github/workflows/ci.yml
Once we have CI deployment sorted to separate account we can re-enable deployment of `master` branch to `nonprod` account again.
> ci: re-enable nonprod AWS account deployment (closes #66)

- .github/workflows/ci.yml
- README.md
- app.py
- datalake/networking_stack.py
- datalake/processing_stack.py
This change is introducing following features:
* possibility to use existing VPC provided by/coming with AWS account
* or in case we create VPC by our networking stack, it is created with limited networking resources (NAT GW, EIPs) if deployment environment is not `prod`. This will reduce cost of networking resources for test and CI deployments and will
reduce usage of EIPs (which is limited to 5 EIPs/AWS account).
Closes: #134
> feat(infra): allow usage of existing VPC coming with AWS account

- datalake/processing_stack.py
`check_stac_metadata` step should run as first one.
> fix(infra): run 'check_stac_metadata' test first in dataset validation

- .github/workflows/deploy.yml
closes #209
Currently, value of `DATALAKE_USERS_AWS_ACCOUNTS_IDS` is set to DS general account and my sandbox account. Needs to be update to correct topo account IDs
> ci: set users aws account IDs for deployment

- reset-dev-env.bash
Necessary when running without `--delete`.
> fix: Reintroduce removing untracked Python packages

- datalake/constructs/batch_job_queue.py
- datalake/constructs/lambda_task.py
- datalake/processing_stack.py
- poetry.lock
- pyproject.toml
By forcing a more recent version we re-enable .dockerignore support
<https://github.com/aws/aws-cdk/releases/tag/v1.73.0>.
This partially reverts commit a097a5abb49281e404309ea8b1f514c01e5dc696.
> fix: Upgrade AWS CDK package

- reset-dev-env.bash
Until we fix <https://github.com/linz/geospatial-data-lake/issues/253>.
> feat: Remove cdk.out as part of dev env reset

- datalake/backend/tests/test_check_stac_metadata_logging.py
- datalake/backend/tests/test_dataset_versions_endpoint_logging.py
By renaming the test class it runs as under pytest without inheriting
from `TestCase`. This makes it possible to use pytest fixtures
<https://docs.pytest.org/en/latest/xunit_setup.html>.
> refactor: Remove dependency on `unittest.TestCase`

- .dockerignore
This uses a bit less disk space for cdk.out. Most importantly it doesn't copy .git and other files/directories which change often, meaning that rebuilds should be faster.
Before: 
```
$ rm --force --recursive cdk.out && time cdk synth && du -hs cdk.out
[…]
3m59.181s
[…]
216M	cdk.out
```
After:
```
$ rm --force --recursive cdk.out && time cdk synth && du -hs cdk.out
[…]
real	4m6.420s
[…]
135M	cdk.out
```
> feat: Copy fewer files when creating CDK Docker assets

- datalake/backend/processing/Dockerfile
As it turns out, the UID/GID don't actually have to map to an existing
user for this to work.
As recommended by
<https://cloudberry.engineering/article/dockerfile-security-best-practices/>,
<https://github.com/hexops/dockerfile> and
<https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html>.
This closes issue https://github.com/linz/geospatial-data-lake/issues/197
> feat: Use non-root user in Docker

- .kodiak.toml
The commit message should include all messages from all commits in the
pull request. See <https://github.com/chdsbd/kodiak/issues/622>.
> fix: Use default GitHub merge commit message

- .github/dependabot.yml
- .pre-commit-config.yaml
See <https://github.com/dependabot/dependabot-core/issues/3263> /
<https://github.com/macisamuele/language-formatters-pre-commit-hooks/issues/53>.
> fix: Change dependabot time configuration value to string

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- backend/check.py
- backend/check_files_checksums/task.py
- backend/check_stac_metadata/task.py
- backend/check_stac_metadata/utils.py
- backend/validation_results_model.py
- backend/validation_summary/task.py
- infrastructure/processing_stack.py
- poetry.lock
- pyproject.toml
- reset-dev-env.bash
- tests/internal_generators.py
- tests/test_check_files_checksums.py
- tests/test_check_files_checksums_logging.py
- tests/test_processing_stack.py
- tests/test_validation_summary.py
Challenges:
- AWS Azure worldwide outage
- [`poetry lock --no-update` still updates packages](https://github.com/python-poetry/poetry/issues/3739)
- [Can't type-annotate pynamodb `MapAttribute` in a `pylint`-compatible way](https://github.com/pynamodb/PynamoDB/issues/920)
- [Lots of "The repository 'https://dl.bintray.com/sbt/debian Release' no longer has a Release file" errors in GitHub Actions](https://github.com/actions/runner/issues/932)
- [GitHub Actions outages](https://www.githubstatus.com/history)
- DisplayLink crashes, [kernel incompatibilities](https://github.com/DisplayLink/evdi/issues?q=is%3Aissue+kernel)
- YAML formatter [clashing](https://github.com/macisamuele/language-formatters-pre-commit-hooks/issues/53) with [Dependabot](https://github.com/dependabot/dependabot-core/issu …
> feat: Implement validation summary task

- .github/pull_request_template.md
Should be easier to use this way.
> docs: Comment out entire sections in PR template by default

- .github/workflows/deploy.yml
- app.py
- backend/version.py
- infrastructure/storage_stack.py
Store deployment version as SSM Parameter instead of CloudFormation stack tag. CloudFormation stack tags are applied recursively to all resources which is causing changes to all resources during all deployments and making CloudFormation changesets unreadable. This change is fixing this issue.
> feat(infra): store deployment version as SSM parameter

- .github/workflows/codeql-analysis.yml
This should make the Dependabot pull request actions pass, because pull
request event actions have write access to save the CodeQL reports. See
<https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push>
for details.
> feat: Run CodeQL on non-master branches only on pull request event

- .github/workflows/codeql-analysis.yml
The default CodeQL setup installs only the non-extras - see for example
<https://github.com/linz/geospatial-data-lake/runs/2335212930>.
> fix: Run CodeQL analysis on optional Python dependencies

- backend/bundle.bash
Avoids some packages complaining about "Using legacy 'setup.py
install'", which presumably is unwanted.
> feat: Install wheel package during bundling

- .github/ISSUE_TEMPLATE/bug_report.md
Escape dashes in markdown comments
Github was formatting the comments as text, so they weren't hidden.
> fix: bug template

- .github/workflows/deploy.yml
- README.md
- infrastructure/constructs/table.py
- infrastructure/removal_policy.py
- infrastructure/storage_stack.py
This change add separate resources removal policy in order to be able to set it to `RETAIN` for CI deployments which are testing production deployment upgrades.
> feat: implement separate configuration for resource removal policy

- .github/workflows/deploy.yml
Should be redundant now that the deploy checks run on automerge labelled
PRs.
> chore: Disable master deploy check

- .github/workflows/deploy.yml
This should ensure that automerge labelled PRs run a deployment check
when pushing to them.
> fix: Match automerge label on any event

- app.py
- infrastructure/api_stack.py
- infrastructure/lambda_layers_stack.py
- infrastructure/lds.py
- infrastructure/processing_stack.py
- infrastructure/staging_stack.py
- infrastructure/storage_stack.py
This change should fix our stack updating issues (should not use CF stack exports) and allows us to keep resources logically separated in stacks (with exception of `botocore` stack which is merged with `storage` stack). This change is based on usage of nested stacks and passing resource information between them using CF parameters.
> refactor(infra): use nested stacks with cross-stack references passed using parameters

- pyproject.toml
- tests/aws_utils.py
- tests/test_processing_stack.py
Lines which may never be reached for good reasons need to be marked as
such, otherwise we'll get intermittent loss of code coverage when the
loop ends early.
See for example https://github.com/linz/geostore/runs/2740976630?check_suite_focus=true
> tests: Avoid intermittent coverage reduction

- backend/Dockerfile
Verified its history
<https://github.com/python-poetry/poetry/commits/master/get-poetry.py>
and generated hash using `curl
https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
| sha256sum`.
> chore: Bump Poetry installer hash

- tests/test_check_stac_metadata.py
`zip` will stop emitting entries once one of the lists have been
exhausted, meaning we might not have tested with all of the expected
entries if the actual entries list was shorter.
> tests: Make sure to check against all expected items

- infrastructure/constructs/processing.py
Allowing the S3 Batch Operations service was not necessary after all,
and caused non-prod deployment to hit a known CDK limitation
<https://github.com/aws/aws-cdk/issues/1578>.
> fix: Allow staging users role assumption only by main principal

- infrastructure/application_stack.py
- infrastructure/constructs/processing.py
Should ensure that its logical ID
<https://docs.aws.amazon.com/cdk/latest/guide/identifiers.html> stays
the same.
> fix: Move staging back to top level

- .github/workflows/test.yml
Only archive it in case of test failure.
This should allow closer inspection of test result details on failure.
To avoid having to merge two reports, we now run the non-infrastructure
tests *twice,* first to verify that none of them use `socket`, and
second to generate the full test report. This should be fine since they
only take a second or two to run.
> feat: Create and archive JUnit report

- backend/notify_status_update/task.py
- backend/step_function_keys.py
- infrastructure/application_stack.py
- infrastructure/constructs/notify.py
- infrastructure/constructs/processing.py
- tests/test_notify_slack.py
Didn't realise that the step function "output" is null when it fails - have to pull or generate data from elsewhere to allow failures to still show validation results etc.
> fix: handle step function returning null on failure

- README.md
- backend/Dockerfile
The original installer is now deprecated
<https://python-poetry.org/blog/announcing-poetry-1.2.0a1/#deprecation-of-the-get-poetrypy-script>.
> feat: Use new Poetry installer

- reset-dev-env.bash
Poetry by default just uses the system Python, even if that is not
supported by the version specifier in pyproject.toml. Poetry prints
> The currently activated Python version 3.9.7 is not supported by the
> project (3.8.10).
> Trying to find and use a compatible version.
> Using python3 (3.8.10)
This message is misleading - it still uses the system Python! See
<https://github.com/python-poetry/poetry/issues/655> for details.
> fix: Use correct Python version for virtualenv

- tests/stac_objects.py
- tests/test_check_stac_metadata.py
Looks like we were validating all objects as collections.
> fix: Verify validity of all minimal STAC objects

- .github/workflows/build.yml
- USAGE.md
- geostore/cli.py
- poetry.lock
- pyproject.toml
- tests/aws_utils.py
- tests/test_cli.py
Contributes towards https://github.com/linz/geospatial-data-lake-team/issues/41.
This only implements a single action, and can be run like `python -m backend.cli dataset create --title=TITLE --description=DESCRIPTION`. This does not include any kind of setup to build and distribute a package to PyPI yet.
- We don't have a common LINZ framework for CLIs, so I've just applied what I consider best practices and documented them in CODING.md
> feat: Add command-line interface (CLI) 1st increment

- .github/workflows/build.yml
- USAGE.md
- geostore/cli.py
- poetry.lock
- pyproject.toml
- tests/test_cli.py
Contributes to https://github.com/linz/geospatial-data-lake-team/issues/41.
- [Poetry packages don't include dependencies](https://stackoverflow.com/q/69763090/96588)
> feat: Expand CLI

- .github/workflows/prod-upgrade-deploy-test.yml
Works around the fact that the current production code relies on the
checksum of a third party file which has changed in the meantime.
See for example https://github.com/linz/geostore/runs/4525566154?check_suite_focus=true.
Helps with #1287.
> fix: Bump Poetry installer checksum in production code

- shell.nix
Copy of #1307 for access to secrets.
> fix: Add `pip` to the Nix-provided Python environment by means of extraPackages

- shell.nix
`$projectDir` refers to the Nix store path, which is the wrong place to
create this.
> fix: Create Python symlink in project directory

- .github/workflows/test.yml
We shouldn't need it anymore since `shell.nix` imports a nixpkgs
archive.
> fix: Remove `NIX_PATH` from `nix-shell` command

- shell.nix
Enables running `nix-shell --pure --run 'pre-commit run --all-files'`.
> feat: Install pre-commit dependencies in Nix shell

- infrastructure/constructs/api.py
This should avoid us ending up with dangling log groups in CI and
development environments, resulting in deployment failures since the
resources already exist.
Closes #1451.
> fix: Apply removal policy to log groups

- geostore/aws_message_attributes.py
- geostore/datasets/create.py
- geostore/populate_catalog/task.py
- geostore/update_dataset_catalog/task.py
- tests/test_cli.py
- tests/test_datasets_endpoint.py
- tests/test_populate_catalog.py
- tests/test_processing_stack.py
- tests/test_update_dataset_catalog.py
Instead, new versions will be referenced directly in the root catalog. This is an intermediary step to allowing Datasets to be updated in place rather than having to create a new dataset version.
> feat: Remove concept of Dataset STAC catalog in geostore

- app.py
- cdk.json
- infrastructure/application_stack.py
- infrastructure/constructs/api.py
- infrastructure/constructs/batch_job_queue.py
- infrastructure/constructs/batch_submit_job_task.py
- infrastructure/constructs/bundled_code.py
- infrastructure/constructs/bundled_lambda_function.py
- infrastructure/constructs/import_file_function.py
- infrastructure/constructs/lambda_config.py
- infrastructure/constructs/lambda_endpoint.py
- infrastructure/constructs/lambda_layers.py
- infrastructure/constructs/lambda_task.py
- infrastructure/constructs/lds.py
- infrastructure/constructs/notify.py
- infrastructure/constructs/opentopo.py
- infrastructure/constructs/processing.py
- infrastructure/constructs/removal_policy.py
- infrastructure/constructs/roles.py
- infrastructure/constructs/staging.py
- infrastructure/constructs/storage.py
- infrastructure/constructs/table.py
- infrastructure/constructs/task_job_definition.py
- infrastructure/networking_stack.py
- poetry.lock
- pyproject.toml
Manual step for this to build:
Enables https://github.com/linz/geostore/issues/1262.
> chore: Upgrade AWS CDK to version 2

- geostore/check_stac_metadata/stac_validators.py
- tests/test_get_latest_extension_schema_version.py
Achieved by finding all the version directories for the extension and
ordering them by version number.
This explicitly only handles `vA.B.C` versions - it does *not* handle
versions like "dev" and "v1.0.0-rc.1". Support for these may need to be
added in the future.
Closes #1446.
> feat: Use latest extension schemas

- infrastructure/constructs/api.py
- infrastructure/constructs/lambda_endpoint.py
This is one of the few differences between production and all other
environments, so it was never tested.
Closes https://github.com/linz/geostore/issues/1726.
> fix: Remove "prod-" prefix from production Lambda endpoints

- geostore/check_files_checksums/task.py
It is not possible to configure AWS Batch job definition parameters to
pass `--key=Ref::some_argument`
<https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#parameters=>,
and `argparse` has a long-standing issue re. not being able to handle
`--key -value`-type key/value pairs
<python/cpython#53580>. The only known
workaround is to use the deprecated `optparse` module.
> fix: Parse argument values starting with hyphen

- cdk.context.json
Information about the CI and NonProd accounts are missing from `cdk.context.json`. This causes CDK to synth the stack twice before deployment (synth -> update context -> synth). Updating this file speed up deployment by about ~4 to 5 minutes.
**Removed**: Unused sandbox account
**Added**: CI and NonProd accounts
> fix: Update cdk context

- .github/workflows/test.yml
This pull request optimises Geostore CDK deployment time in GitHub Actions workflow by calling `aws cloudformation delete-stack` rather than `cdk destroy`
Running `cdk destroy` causes cdk to parse through the stack again before attempting to tear it down. It waits for the stack to be completely destroyed before finishing the workflow. ` aws cloudformation delete-stack` is a simple api call that doesn't wait for a response. It allows the call to be made to aws to terminate the stack. This shaves about ~5 to 6 minutes off the workflow runtime.
> refactor: Speed up CDK

- USAGE.md
The examples provided are for `AWS CLI v1` API calls. Running these commands on `CLI v2` returns non-helpful error messages. Updating `USAGE.md` to include `v2` API calls.
This PR would hopefully save someone else some time from chasing down base-64 errors.
> docs: Include cli v2 API calls

- CODING.md
- geostore/dataset_versions/create.py
`utcnow` returns a datetime without a time zone, which makes it risky for any kind of use. We should avoid it and `utcfromtimestamp`. See <https://blog.ganssle.io/articles/2019/11/utcnow.html> for details.
> fix: Use UTC datetimes

- reset-dev-env.bash
`--remove-untracked`: Remove dependencies not presented in the lock file. (Deprecated, use `--sync` instead)
https://python-poetry.org/docs/cli/
> feat: Update poetry remove-untracked option flag to sync

- .github/release.yml
Changelog typically outlines what has changed since the last release. We can GitHub to automatically generate release notes every time we do a release; however, this is often filled with commits created by dependabot (bump package version). This PR excludes dependabot commits from future release notes. 
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes
> feat: Remove dependabot commits from changelog

- .github/workflows/codeql-analysis.yml
- .github/workflows/package-cli.yml
- .github/workflows/prod-upgrade-deploy-test.yml
- .github/workflows/test.yml
By default, GitHub Action will checkout the merge commit created for the pull request rather than the actual commit used to create the pull request. There is a slim but non zero chance that this could cause some flaky tests. This PR is to get GitHub Actions to checkout pull request HEAD commit instead of merge commit.
**Note:** This only applies to `pull_request` as per [GitHub documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request). Since geostore's workflow can be triggered by different events, a conditional step is added to ensure this change only applies to `pull_request`. 
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
https://github.com/actions/checkout/issues/261 …
> fix: Checkout pull request HEAD commit instead of merge commit

- infrastructure/constructs/processing.py
We should probably be logging Step Function State Machine events to CloudWatch. This would help with troubleshooting. 
This complies with [AwsSolutions-SF1](https://github.com/cdklabs/cdk-nag/blob/main/RULES.md). 
Example log snippet:
```
{
"id": "4",
"type": "LambdaFunctionStarted",
"details": {},
"previous_event_id": "3",
"event_timestamp": "1668385713883",
"execution_arn": "arn:aws:states:ap-southeast-2:12345:execution:processinggeostoredatasetversioncreation65D71092-W9Bi3T8DiGui:2022-11-14T00-28-33-438Z_59Z1PGC394K1FR4H"
}
{
"id": "5",
"type": "LambdaFunctionFailed",
"details": {
"cause": "{\"errorMessage\": \"\", \"errorType\": \"InvalidSTACRootTypeError\", \"requestId\": \"ef0b96d2-560b-44fc-9b67-b69f4800b735\", \"stackTrace\": [\"  File …
```
> feat: Log Step Function State Machine events

- .github/workflows/codeql-analysis.yml
- .github/workflows/package-cli.yml
- .github/workflows/prod-upgrade-deploy-test.yml
- .github/workflows/test.yml
Geostore CI takes a while to complete. In cases where a new commit is pushed to an existing pull request branch before the previous GitHub action workflow completes, a new workflow is triggered; leaving the old workflow to run its course even though it is no longer relevant (in most cases). This PR limits workflow concurrency by cancelling previous workflow.
This resolves #2290 
References:
https://docs.github.com/en/actions/using-jobs/using-concurrency
https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre/72408109#72408109
> feat: Ensure only one GitHub action workflow is running

- .github/workflows/test.yml
There is no mechanism in place to clean up CloudWatch Log Groups created by Geostore. While the logs itself can be set to expire, the Log Groups are kept forever. This presents a problem in CI. 
There isn't an elegant way to delete log groups within CDK on stack teardown currently (this may change in the future). 
This PR runs `aws logs delete-log-group` command at the end of the CI to cull log groups older than 1 week old (from previous CI runs). **This is a temporary work around until a better solution is found.** 
Note: A `--no-paginate` option is added to limit the number of queries (~50). This prevents rate limiting as well as stops a potentially endless number of results being returned by AWS (which would result in a very log running workflow). This means only a maximum number of 50 …
> feat: Delete CloudWatch Log Groups over a week old

- .github/workflows/test.yml
It is possible that the `delete-log-group` command to gets into a race condition when more than one CI runs at the same time (i.e. it tries to delete the same log group that another CI has just deleted moments ago). This causes `xargs` to throw a `123` exit code, which, in turn causes GitHub actions to fail. Ignoring this exit code is one way to get around this problem as a workaround. It should be noted that this implementation prevents other `xargs` errors with the same exit code from being raised.
> fix: Delete Cloudwatch log groups race condition

- infrastructure/constructs/processing.py
Vended log groups created by state-machine should be destroyed on stack teardown in ci and non prod environments. This is to keep the number of log groups manageable (especially since new log groups are created with each ci seed).
> fix: Delete vended log groups in ci and non-prod

- geostore/s3_utils.py
As per
<https://bandit.readthedocs.io/en/latest/plugins/b324_hashlib.html>.
- [pylint 2.14.2 complains about the new argument](https://github.com/PyCQA/pylint/issues/6017)
> fix: Mark insecure hash use as such

- infrastructure/application_stack.py
- infrastructure/constructs/bundled_code.py
`lru_cache` is a bit of a hacky workaround to prevent values from being updated within the context of setting up a `lambda_packaging_dir` using `mkdtemp` (that is persistent throughout a particular run). This isn't how it is intended to be used. A class variable would provide the same outcome whilst keeping the code a bit tidier.
> refactor: Use class variable instead of lru_cache

- pyproject.toml
> chore: Delete reference to bundle.bash

- .github/workflows/mutation-test.yml
- .github/workflows/package-cli.yml
- .github/workflows/test.yml
As per
<https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/>.
> refactor: Stop using deprecated `set-output` command

- .github/workflows/test.yml
Cuts ~2 minutes off of the linting step (https://github.com/linz/geostore/actions/runs/3906625303/jobs/6675012868 vs https://github.com/linz/geostore/actions/runs/3906625303/jobs/6675354730).
> feat: Cache pre-commit
